-- 默认选项种子数据 (仅全新安装/开发环境使用;迁移现有数据时 options 表整体导入,不执行本文件)
-- 来源: config/options.php (49 项) + version (config/app.php = 6.0.2)
--      + 2025_06_29_064944 max_texture_width = 8192
-- 与原迁移 2016_11_18_134542_import_options.php 行为一致:
--   announcement 中 {version} → 6.0.2;copyright_text 中 {year} → 当前年份
INSERT INTO options (option_name, option_value) VALUES
    ('site_url', ''),
    ('site_name', 'Blessing Skin'),
    ('site_description', 'Open-source PHP Minecraft Skin Hosting Service'),
    ('register_with_player_name', 'true'),
    ('require_verification', 'false'),
    ('regs_per_ip', '3'),
    ('announcement', 'Welcome to Blessing Skin 6.0.2!'),
    ('home_pic_url', './app/bg.webp'),
    ('custom_css', ''),
    ('custom_js', ''),
    ('player_name_rule', 'official'),
    ('custom_player_name_regexp', ''),
    ('player_name_length_min', '3'),
    ('player_name_length_max', '16'),
    ('user_initial_score', '1000'),
    ('sign_gap_time', '24'),
    ('sign_score', '10,100'),
    ('score_per_storage', 'true'),
    ('private_score_per_storage', '10'),
    ('return_score', 'true'),
    ('score_per_player', '100'),
    ('sign_after_zero', 'false'),
    ('version', '6.0.2'),
    ('copyright_text', '<b>Copyright &copy; 2026 <a href="{site_url}">{site_name}</a>.</b> All rights reserved.'),
    ('auto_del_invalid_texture', 'false'),
    ('allow_downloading_texture', 'true'),
    ('texture_name_regexp', ''),
    ('cache_expire_time', '31536000'),
    ('max_upload_file_size', '1024'),
    ('force_ssl', 'false'),
    ('auto_detect_asset_url', 'true'),
    ('plugins_enabled', ''),
    ('copyright_prefer', '0'),
    ('score_per_closet_item', '0'),
    ('favicon_url', 'app/favicon.ico'),
    ('score_award_per_texture', '0'),
    ('take_back_scores_after_deletion', 'true'),
    ('score_award_per_like', '0'),
    ('meta_keywords', ''),
    ('meta_description', ''),
    ('meta_extras', ''),
    ('cdn_address', ''),
    ('recaptcha_sitekey', ''),
    ('recaptcha_secretkey', ''),
    ('recaptcha_invisible', 'false'),
    ('reporter_score_modification', '0'),
    ('reporter_reward_score', '0'),
    ('content_policy', ''),
    ('transparent_navbar', 'false'),
    ('status_code_for_private', '403'),
    ('navbar_color', 'cyan'),
    ('sidebar_color', 'dark-maroon'),
    ('max_texture_width', '8192');
